- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import all the variables
      include_vars: vars/vpc-vars
    - name: create a VPC with dedicated tenancy and a couple of tags
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region_name}}"
        dns_support: yes
        dns_hostnames: yes
        state: "{{state}}"
        tenancy: default
      register: vpcout
    - name: Create public subnets
      ec2_vpc_subnet:
        state: "{{state}}"
        region: "{{region_name}}"
        az: "{{zone1}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{pubsubnet1}}"
        resource_tags:
          Name: "Public_sub-1"
      register: "subnetout"
    - name: Create public subnets
      ec2_vpc_subnet:
        state: "{{state}}"
        region: "{{region_name}}"
        az: "{{zone2}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{pubsubnet2}}"
        resource_tags:
          Name: "Public_sub-2"
      register: "subnetout2"
    - name: Create public subnets
      ec2_vpc_subnet:
        state: "{{state}}"
        region: "{{region_name}}"
        az: "{{zone3}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{pubsubnet3}}"
        resource_tags:
          Name: "Public_sub-3"
      register: "subnetout3"
    - name: Create private subnets
      ec2_vpc_subnet:
        state: "{{state}}"
        region: "{{region_name}}"
        az: "{{zone1}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{privsubnet1}}"
        resource_tags:
          Name: "Priv_sub-1"
      register: "privsubnetout1"
    - name: Create private subnets
      ec2_vpc_subnet:
        state: "{{state}}"
        region: "{{region_name}}"
        az: "{{zone2}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{privsubnet2}}"
        resource_tags:
          Name: "Priv_sub-2"
      register: "privsubnetout2"
    - name: Create private subnets
      ec2_vpc_subnet:
        state: "{{state}}"
        region: "{{region_name}}"
        az: "{{zone3}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{privsubnet3}}"
        resource_tags:
          Name: "Priv_sub-3"
      register: "privsubnetout3"

    - name: Create internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        state: "{{state}}"
        region: "{{region_name}}"
        tags:
          Name: "Vpc-igw"
      register: "igw"

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region_name}}"
        tags:
          Name: "Vprofile-route"
        subnets:
          - "{{subnetout.subnet.id}}"
          - "{{subnetout2.subnet.id}}"
          - "{{subnetout3.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw.gateway_id}}"
      register: "public_route_table"
