---
- name: build and copy artifacts
  hosts: localhost
  connection: local
  tasks:
    - name: install required packages
      apt:
        name: {{item}}
        state: present
      loop:
        - maven
        - git
        - openjdk-8-jdk

    - name: clone from a git repository
      git:
         repo: https://github.com/devopshydclub/vprofile-project.git
         dest: provision_stack/vprofile-repo
      register: git_repo

    - name: run maven install
      command: mvn install
      args:
        chdir: vprofile-repo
      when: git_repo.changed
      register: mvn_out

    - name: copy artifact to files directory
      copy:
        src: "{{ item }}"
        dest: "file/ROOT.war"
      with_fileglob:
         - "vprofile-repo/target/*.war"

    - name: copy sql to files directory
      copy:
        src: vprofile-repo/src/main/resources/db_backup.sql
        dest: files/db_backup.sql
