---
- name: Setup Mysql with accounts db and remote login
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: import db variables
      include_vars: group_vars/dbvars

    - name: copy sql file from local to remote
      copy:
        src: file/db_backup.sql
        dest: tmp/db_backup.sql

    - name: deploy to the my sql databse
      mysql_db:
        name: "{{db_name}}"
        state: import
        login_user: "{{db_user}}"
        login_password: "{{db_password}}"
        target: /tmp/db_backup.sql
      notify:
        - restartmysql

  handlers:
    - name: restartmysql
      service:
        name: mysql
        state: restarted
